## Load Libs

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import label_binarize
from datetime import datetime as dt
import matplotlib.pyplot as plt
%matplotlib inline

## Functions

In [3]:
def normalize(x):
    return (x-np.mean(x))/np.std(x)

def extract_date_variables(input_data, date_in_index=False):
    
    '''This function extracts data variables from a series or index of a series. Returns
        a DataFrame with extracted variables'''

    if date_in_index:
        
        input_data['weeknr'] = map(lambda x: str(x), input_data.index.week)
        input_data['year'] = map(lambda x: str(x), input_data.index.year)
        input_data['month'] = map(lambda x: str(x), input_data.index.month)

        input_data['week_year'] = input_data['weeknr'] + '_' + input_data['year']
        input_data['month_year'] = input_data['month'] + '_' + input_data['year']

        return input_data
    
    else:
        output_data = input_data.to_frame(name='timestamp')
        
        output_data['weeknr'] = map(lambda x: str(x.week), output_data['timestamp'])
        output_data['year'] = map(lambda x: str(x.year), output_data['timestamp'])
        output_data['month'] = map(lambda x: str(x.month), output_data['timestamp'])

        output_data['week_year']  = output_data['weeknr'] + '_' + output_data['year']
        output_data['month_year'] = output_data['month'] + '_' + output_data['year']

        return output_data

## Load Data

In [4]:
df_macro = pd.read_csv('~/Desktop/sberbank/macro_pred.csv', sep=';')
df_train = pd.read_csv('~/Desktop/sberbank/train.csv')
df_test = pd.read_csv('~/Desktop/sberbank/test.csv')

In [5]:
df_test

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,cafe_count_5000_price_1500,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000
0,30474,2015-07-01,39.00,20.70,2,9,1,1998.0,1,8.9,...,8,0,0,0,1,10,1,0,14,1
1,30475,2015-07-01,79.20,NaN,8,17,1,0.0,3,1.0,...,4,1,1,0,2,11,0,1,12,1
2,30476,2015-07-01,40.50,25.10,3,5,2,1960.0,2,4.8,...,42,11,4,0,10,21,0,10,71,11
3,30477,2015-07-01,62.80,36.00,17,17,1,2016.0,2,62.8,...,1,1,2,0,0,10,0,0,2,0
4,30478,2015-07-01,40.00,40.00,17,17,1,0.0,1,1.0,...,5,1,1,0,2,12,0,1,11,1
5,30479,2015-07-01,48.43,NaN,21,1,1,2015.0,1,1.0,...,143,99,57,12,23,42,1,13,123,7
6,30480,2015-07-01,38.80,NaN,15,17,1,NaN,1,1.0,...,12,7,2,0,5,14,0,3,17,2
7,30481,2015-07-01,43.10,NaN,5,0,1,NaN,1,0.0,...,5,2,2,0,3,12,0,0,6,3
8,30482,2015-07-01,45.40,28.50,9,12,5,1972.0,2,6.0,...,3,1,0,0,1,7,0,0,7,0
9,30483,2015-07-01,43.30,43.30,7,22,1,0.0,1,1.0,...,5,2,1,0,2,9,0,0,7,0
10,30484,2015-07-01,37.26,NaN,4,15,4,2017.0,1,8.0,...,40,13,3,0,9,29,0,7,63,13
11,30485,2015-07-01,39.20,10.00,11,17,4,0.0,1,10.0,...,5,1,1,0,2,12,0,1,11,1
12,30486,2015-07-01,37.04,37.04,14,15,6,2015.0,1,1.0,...,1,1,0,0,2,7,0,0,0,0
13,30487,2015-07-01,39.80,18.90,4,17,1,2013.0,1,9.9,...,4,1,0,0,4,5,0,0,5,1
14,30488,2015-07-01,69.30,NaN,7,1,1,NaN,2,1.0,...,1,1,2,0,0,7,0,0,2,0
15,30489,2015-07-02,69.30,NaN,10,0,1,NaN,2,0.0,...,4,2,2,0,2,9,0,0,7,2
16,30490,2015-07-02,117.40,NaN,10,0,1,NaN,3,0.0,...,36,14,3,0,12,20,0,5,78,8
17,30491,2015-07-02,94.50,61.90,2,12,1,2000.0,4,10.3,...,152,76,17,4,30,51,1,21,102,9
18,30492,2015-07-02,62.50,32.60,7,17,1,2013.0,2,12.9,...,4,1,0,0,4,5,0,0,4,1
19,30493,2015-07-02,77.70,52.60,2,5,5,1958.0,3,8.5,...,118,50,9,2,15,36,1,10,102,10
20,30494,2015-07-02,64.00,64.00,4,17,1,0.0,2,10.0,...,5,1,1,0,2,12,0,1,11,1
21,30495,2015-07-02,67.20,45.10,14,16,5,1978.0,3,7.7,...,72,26,4,0,9,31,1,10,70,9
22,30496,2015-07-02,99.88,NaN,4,9,1,NaN,3,1.0,...,38,10,3,0,10,9,0,0,38,4
23,30497,2015-07-02,79.20,NaN,6,17,1,NaN,3,1.0,...,6,3,1,0,3,9,0,1,10,2
24,30498,2015-07-02,32.50,18.70,4,9,1,1971.0,1,6.6,...,24,6,3,0,9,17,0,10,55,11
25,30499,2015-07-02,65.10,46.00,11,12,1,1978.0,3,6.5,...,42,11,4,0,13,25,1,0,58,5
26,30500,2015-07-02,74.00,41.70,17,17,1,2016.0,2,1.0,...,34,12,3,0,12,10,0,1,49,5
27,30501,2015-07-02,45.80,29.60,6,9,1,1969.0,2,6.1,...,45,14,5,0,11,14,0,1,62,8
28,30502,2015-07-02,32.00,32.00,15,17,1,2017.0,1,10.0,...,3,1,0,0,1,6,0,0,6,1
29,30503,2015-07-02,37.80,19.10,13,16,1,1982.0,1,8.1,...,65,55,20,1,11,26,1,7,101,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7632,38106,2016-05-20,44.40,27.90,6,9,1,1967.0,2,5.9,...,51,12,4,0,14,21,1,0,65,7
7633,38107,2016-05-20,37.93,37.93,3,13,1,0.0,1,0.0,...,3,1,0,0,1,6,0,0,6,1
7634,38108,2016-05-20,64.60,46.20,6,16,5,1984.0,3,7.7,...,96,38,3,1,6,36,1,6,79,8
7635,38109,2016-05-20,42.23,1.00,11,17,1,NaN,1,1.0,...,27,7,3,0,8,18,0,8,72,10
7636,38110,2016-05-21,57.90,36.90,2,3,1,1953.0,3,7.8,...,0,0,0,0,0,2,0,0,0,0
7637,38111,2016-05-21,54.09,54.09,12,17,4,2017.0,2,10.0,...,1,2,1,0,0,10,0,0,0,0
7638,38112,2016-05-21,36.50,NaN,13,17,1,NaN,1,0.0,...,2,3,1,0,0,8,0,0,3,2
7639,38113,2016-05-21,51.30,30.60,5,17,1,1996.0,2,8.3,...,26,7,2,0,9,19,0,2,52,10
7640,38114,2016-05-23,77.51,1.00,4,1,1,1.0,3,1.0,...,636,371,141,26,150,249,2,105,203,13
7641,38115,2016-05-23,36.00,36.00,10,17,1,2015.0,1,11.0,...,2,3,1,0,0,8,0,0,3,2
7642,38116,2016-05-23,43.71,43.71,6,20,1,NaN,1,1.0,...,42,25,3,0,14,29,1,4,90,6
7643,38117,2016-05-23,64.30,33.90,15,17,1,2013.0,2,12.9,...,6,3,1,0,4,11,0,1,11,2
7644,38118,2016-05-23,48.40,30.20,4,30,6,2012.0,1,12.7,...,201,87,24,3,74,107,1,23,112,15
7645,38119,2016-05-23,39.90,NaN,11,16,1,2016.0,1,1.0,...,2,3,1,0,0,7,0,0,3,2
7646,38120,2016-05-23,69.70,1.00,8,1,4,2016.0,2,1.0,...,8,3,2,0,4,5,0,0,8,1
7647,38121,2016-05-23,39.60,18.90,22,25,1,2014.0,1,9.1,...,158,100,24,10,29,70,1,23,127,12
7648,38122,2016-05-23,33.89,1.00,3,1,1,1.0,1,1.0,...,526,298,98,16,130,228,2,89,185,14
7649,38123,2016-05-24,27.27,NaN,14,1,1,NaN,1,1.0,...,309,161,55,5,87,141,2,36,153,12
7650,38124,2016-05-24,64.00,1.00,12,17,1,2017.0,2,1.0,...,5,1,1,0,2,12,0,1,11,1
7651,38125,2016-05-24,54.60,32.20,16,16,1,2000.0,2,9.3,...,21,5,1,0,9,24,0,3,48,7
7652,38126,2016-05-24,62.39,40.00,4,16,1,2016.0,2,12.0,...,224,93,22,2,68,107,1,29,131,14
7653,38127,2016-05-25,19.91,1.00,8,1,1,1.0,1,1.0,...,526,298,98,16,130,228,2,89,185,14
7654,38128,2016-05-25,23.56,1.00,1,1,1,1.0,1,1.0,...,0,0,0,0,0,4,0,0,0,2
7655,38129,2016-05-25,41.68,1.00,13,17,1,NaN,1,1.0,...,1,1,0,0,0,5,0,0,3,1
7656,38130,2016-05-26,50.28,1.00,3,17,1,NaN,1,1.0,...,17,7,0,0,4,13,0,2,29,2
7657,38131,2016-05-26,52.20,31.80,10,12,5,1973.0,2,9.1,...,81,28,1,1,8,39,2,3,75,12
7658,38132,2016-05-28,54.09,NaN,14,0,1,NaN,2,0.0,...,1,2,1,0,0,10,0,0,0,0
7659,38133,2016-05-30,41.08,1.00,12,1,1,1.0,1,1.0,...,636,371,141,26,150,249,2,105,203,13
7660,38134,2016-05-30,34.80,19.80,8,9,5,1977.0,1,6.4,...,16,7,2,0,5,11,0,2,43,10
7661,38135,2016-05-30,63.00,43.80,5,5,1,1973.0,3,7.1,...,31,11,1,0,6,26,1,4,42,11

## Process Data

In [6]:
df_train['timestamp'] = pd.to_datetime(df_train['timestamp'])
df_test['timestamp'] = pd.to_datetime(df_test['timestamp'])

In [7]:
time_data_train = extract_date_variables(df_train['timestamp'])[['timestamp', 'month_year']]
time_data_test  = extract_date_variables(df_test['timestamp'])[['timestamp', 'month_year']]

df_train['month_year'] = time_data_train['month_year']
df_test['month_year'] = time_data_test['month_year']

Merge with macro price

In [8]:
df_train = df_train.merge(df_macro, on='month_year')
df_test  = df_test.merge(df_macro, on='month_year')

In [9]:
y_train = np.log(df_train['price_doc']+1).copy()
X_train = df_train.drop(['price_doc', 'id'], axis=1).copy()

Feature cleaning

In [10]:
def clean_bank(raw_data):
    
    raw_data_features = raw_data.copy()
    
    fsq = np.log(raw_data['full_sq']+1)
    fsq[fsq <1.5] = np.nan
    fsq[fsq >8] = np.nan
    raw_data_features['full_sq'] = fsq

    lsq = np.log(raw_data['life_sq']+1)
    lsq[lsq <1.5] = np.nan
    lsq[lsq >8] = np.nan
    raw_data_features['life_sq'] = lsq


    flr = raw_data_features['floor']
    mflr = raw_data_features['max_floor']

    flr[flr==0] = np.nan
    mflr[mflr==0] = np.nan

    raw_data_features['floor']=flr
    raw_data_features['max_floor']=mflr

    building_type = pd.cut(mflr, np.append(np.arange(0,30), 200))
    raw_data_features['build_type_maxfloor'] = building_type

    # make first floor and last floor as separate var
    raw_data_features['first_floor'] = flr==1
    raw_data_features['last_floor'] = (flr==mflr)

    raw_data.loc[raw_data['material']==3, 'material'] = np.nan
    raw_data_features['material'] = raw_data['material']

    byr = raw_data['build_year'].copy()
    byr[(byr<1000) | (byr>2020)]=np.nan 
    raw_data_features['build_year'] = np.log(byr)

    room_cat = pd.cut(raw_data['num_room'], np.append(np.arange(0,7), 20))
    raw_data_features['num_room']=room_cat

    ksq = raw_data['kitch_sq'].copy()
    ksq[(ksq>250) | (ksq<2)] = np.nan
    raw_data_features['kitch_sq'] = np.log(ksq+1)

    stat = raw_data['state'].copy()
    stat[stat==33] = 3
    raw_data_features['state'] = stat

    
    X_clean = raw_data_features[['full_sq', 'life_sq', 'floor', 'material', 'build_year' ,
                                 'num_room', 'kitch_sq', 'state', 'product_type', 'sub_area',
                                 'first_floor', 'last_floor','build_type_maxfloor', 'macro_price']]

    X_clean['num_room'] = X_clean.num_room.astype('object')
    X_clean['build_type_maxfloor'] = X_clean.build_type_maxfloor.astype('object')


    X_clean['first_floor'] = X_clean.first_floor.astype('int')
    X_clean['last_floor'] = X_clean.last_floor.astype('int')
    
    
    # replace missings
    X_clean.fillna(X_clean.mean(), inplace=True)
    X_clean.loc[X_clean['num_room'].isnull(),'num_room'] = 'not_available'
    X_clean.loc[X_clean['build_type_maxfloor'].isnull(),'build_type_maxfloor'] = 'not_available'
    
    
    # encode dummies
    def makeDum(ser, naam):
        if len(np.unique(ser)) == 2:
            return pd.DataFrame(label_binarize(ser, classes=np.unique(ser)), index=ser.keys(), columns=[naam+'_'+np.unique(ser)[0]] )
        else:
            return pd.DataFrame(label_binarize(ser, classes=np.unique(ser)), index=ser.keys(), columns=naam+'_'+np.unique(ser)) 


    X_clean = X_clean.merge(makeDum(X_clean.num_room, 'num_room').iloc[:,:-1], left_index=True, right_index=True)
    X_clean = X_clean.drop('num_room', axis=1)

    X_clean = X_clean.merge(makeDum(X_clean.product_type, 'product_type').iloc[:,:-1], left_index=True, right_index=True)
    X_clean = X_clean.drop('product_type', axis=1)

    X_clean = X_clean.merge(makeDum(X_clean.sub_area, 'sub_area').iloc[:,:-1], left_index=True, right_index=True)
    X_clean = X_clean.drop('sub_area', axis=1)
        
    X_clean = X_clean.merge(makeDum(X_clean.build_type_maxfloor, 'build_type_maxfloor').iloc[:,:-1], left_index=True, right_index=True)
    X_clean = X_clean.drop('build_type_maxfloor', axis=1)
    
    
    return X_clean

In [11]:
X_train_clean = clean_bank(X_train)

/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [12]:
# there is suddenly an NA in owner-occupier variable

df_test.loc[df_test['product_type'].isnull(), 'product_type'] = df_test['product_type'].mode()[0]

X_test_clean = clean_bank(df_test)

/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/ipykernel/__main__.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [13]:
# colnames do not match

print X_train_clean.shape
print X_test_clean.shape

missing_names = list(set(X_train_clean.columns) - set(X_test_clean.columns))
print missing_names

X_train_clean = X_train_clean.drop(labels=missing_names, axis=1)
X_train_clean

(30471, 473)
(7662, 472)
['num_room_(6, 20]', 'sub_area_Poselenie Klenovskoe']

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,kitch_sq,state,area_m,...,"build_type_maxfloor_(27, 28]","build_type_maxfloor_(28, 29]","build_type_maxfloor_(29, 200]","build_type_maxfloor_(3, 4]","build_type_maxfloor_(4, 5]","build_type_maxfloor_(5, 6]","build_type_maxfloor_(6, 7]","build_type_maxfloor_(7, 8]","build_type_maxfloor_(8, 9]","build_type_maxfloor_(9, 10]"
0,2011-08-20,3.784190,3.332205,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,6.407578e+06,...,0,0,0,0,0,0,0,0,0,0
1,2011-08-23,3.555348,2.995732,3.0,12.898423,1.827065,7.593495,2.165884,2.105251,9.589337e+06,...,0,0,0,0,0,0,0,0,0,0
2,2011-08-27,3.784190,3.401197,2.0,12.898423,1.827065,7.593495,2.165884,2.105251,4.808270e+06,...,0,0,0,0,0,0,0,0,0,0
3,2011-09-01,4.499810,3.931826,9.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.258354e+07,...,0,0,0,0,0,0,0,0,0,0
4,2011-09-05,4.356709,4.356709,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,8.398461e+06,...,0,0,0,0,0,0,0,0,0,0
5,2011-09-06,4.219508,3.850148,14.0,12.898423,1.827065,7.593495,2.165884,2.105251,7.506452e+06,...,0,0,0,0,0,0,0,0,0,0
6,2011-09-08,3.258097,2.708050,10.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.032047e+07,...,0,0,0,0,0,0,0,0,0,0
7,2011-09-09,3.806662,3.806662,5.0,12.898423,1.827065,7.593495,2.165884,2.105251,6.407578e+06,...,0,0,0,0,0,0,0,0,0,0
8,2011-09-10,3.761200,3.332205,5.0,12.898423,1.827065,7.593495,2.165884,2.105251,4.787424e+06,...,0,0,0,0,0,0,0,0,0,0
9,2011-09-13,3.610918,3.091042,9.0,12.898423,1.827065,7.593495,2.165884,2.105251,5.235177e+07,...,0,0,0,0,0,0,0,0,0,0
10,2011-09-16,3.610918,2.995732,12.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.488362e+07,...,0,0,0,0,0,0,0,0,0,0
11,2011-09-16,3.663562,2.995732,11.0,12.898423,1.827065,7.593495,2.165884,2.105251,7.632940e+06,...,0,0,0,0,0,0,0,0,0,0
12,2011-09-17,3.784190,3.367296,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,5.235177e+07,...,0,0,0,0,0,0,0,0,0,0
13,2011-09-19,3.465736,3.465736,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.163805e+07,...,0,0,0,0,0,0,0,0,0,0
14,2011-09-19,3.465736,3.091042,3.0,12.898423,1.827065,7.593495,2.165884,2.105251,8.993640e+06,...,0,0,0,0,0,0,0,0,0,0
15,2011-09-20,3.951244,3.465736,15.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.175477e+07,...,0,0,0,0,0,0,0,0,0,0
16,2011-09-20,3.871201,3.465736,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,7.984444e+06,...,0,0,0,0,0,0,0,0,0,0
17,2011-09-20,3.761200,3.367296,2.0,12.898423,1.827065,7.593495,2.165884,2.105251,5.293465e+06,...,0,0,0,0,0,0,0,0,0,0
18,2011-09-22,4.094345,3.526361,10.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.488362e+07,...,0,0,0,0,0,0,0,0,0,0
19,2011-09-22,3.806662,3.401197,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.428699e+07,...,0,0,0,0,0,0,0,0,0,0
20,2011-09-22,4.317488,3.806662,10.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.531990e+07,...,0,0,0,0,0,0,0,0,0,0
21,2011-09-22,3.688879,3.688879,7.0,12.898423,1.827065,7.593495,2.165884,2.105251,7.887684e+06,...,0,0,0,0,0,0,0,0,0,0
22,2011-09-23,3.891820,3.555348,6.0,12.898423,1.827065,7.593495,2.165884,2.105251,9.249237e+06,...,0,0,0,0,0,0,0,0,0,0
23,2011-09-23,3.496508,2.944439,3.0,12.898423,1.827065,7.593495,2.165884,2.105251,6.879020e+06,...,0,0,0,0,0,0,0,0,0,0
24,2011-09-23,3.555348,2.995732,11.0,12.898423,1.827065,7.593495,2.165884,2.105251,7.887684e+06,...,0,0,0,0,0,0,0,0,0,0
25,2011-09-24,3.828641,3.401197,9.0,12.898423,1.827065,7.593495,2.165884,2.105251,6.982964e+06,...,0,0,0,0,0,0,0,0,0,0
26,2011-09-26,3.583519,3.044522,4.0,12.898423,1.827065,7.593495,2.165884,2.105251,1.005305e+07,...,0,0,0,0,0,0,0,0,0,0
27,2011-09-26,3.663562,3.044522,6.0,12.898423,1.827065,7.593495,2.165884,2.105251,8.591335e+06,...,0,0,0,0,0,0,0,0,0,0
28,2011-09-26,4.304065,3.663562,15.0,12.898423,1.827065,7.593495,2.165884,2.105251,8.659075e+06,...,0,0,0,0,0,0,0,0,0,0
29,2011-09-27,3.761200,3.332205,3.0,12.898423,1.827065,7.593495,2.165884,2.105251,8.338438e+06,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30441,2015-06-27,4.736198,3.466464,26.0,26.000000,1.000000,7.608374,2.165884,1.000000,7.307411e+06,...,0,0,0,0,0,0,0,0,0,0
30442,2015-06-27,3.713572,3.713572,2.0,12.000000,4.000000,7.608374,2.397895,1.000000,2.149409e+07,...,0,0,0,0,0,0,0,0,0,0
30443,2015-06-27,4.382027,3.466464,17.0,17.000000,1.000000,7.593495,4.382027,1.000000,1.132409e+07,...,0,0,0,0,0,0,0,0,0,0
30444,2015-06-27,4.454347,3.466464,20.0,25.000000,4.000000,7.608871,2.165884,1.000000,1.258354e+07,...,0,0,0,0,0,0,0,0,0,0
30445,2015-06-27,3.871201,3.871201,19.0,25.000000,1.000000,7.608871,2.165884,1.000000,9.629358e+06,...,0,0,0,0,0,0,0,0,0,0
30446,2015-06-27,4.418841,4.418841,8.0,8.000000,6.000000,7.609367,2.165884,1.000000,6.677245e+07,...,0,0,0,0,0,0,0,1,0,0
30447,2015-06-27,4.174387,3.466464,15.0,17.000000,1.000000,7.593495,2.165884,2.105251,1.132409e+07,...,0,0,0,0,0,0,0,0,0,0
30448,2015-06-27,4.317488,3.466464,8.0,17.000000,1.000000,7.593495,2.165884,2.105251,4.036700e+07,...,0,0,0,0,0,0,0,0,0,0
30449,2015-06-27,3.871201,3.871201,7.0,25.000000,1.000000,7.608374,2.165884,1.000000,9.629358e+06,...,0,0,0,0,0,0,0,0,0,0
30450,2015-06-29,4.189655,3.466464,5.0,12.898423,1.000000,7.593495,2.165884,2.105251,1.005305e+07,...,0,0,0,0,0,0,0,0,0,0
30451,2015-06-29,3.637586,3.466464,3.0,3.000000,1.000000,7.593495,2.165884,1.000000,1.487016e+08,...,0,0,0,0,0,0,0,0,0,0
30452,2015-06-29,3.663562,2.995732,7.0,17.000000,1.000000,7.603898,2.079442,3.000000,1.752651e+07,...,0,0,0,0,0,0,0,0,0,0
30453,2015-06-29,3.828641,3.466464,6.0,15.000000,6.000000,7.608374,2.165884,1.000000,2.615514e+07,...,0,0,0,0,0,0,0,0,0,0
30454,2015-06-29,3.713572,3.295837,3.0,9.000000,2.000000,7.586804,1.791759,3.000000,8.659075e+06,...,0,0,0,0,0,0,0,0,1,0
30455,2015-06-29,4.382027,4.382027,3.0,3.000000,1.000000,7.593495,2.165884,2.105251,2.553630e+07,...,0,0,0,0,0,0,0,0,0,0
30456,2015-06-29,3.970292,3.433987,8.0,14.000000,1.000000,7.596894,2.197225,2.000000,1.258354e+07,...,0,0,0,0,0,0,0,0,0,0
30457,2015-06-29,4.077537,3.784190,7.0,9.000000,1.000000,7.590347,1.945910,3.000000,8.338438e+06,...,0,0,0,0,0,0,0,0,1,0
30458,2015-06-29,3.931826,3.466464,7.0,7.000000,1.000000,7.608374,2.165884,1.000000,4.036700e+07,...,0,0,0,0,0,0,1,0,0,0
30459,2015-06-29,3.951244,3.466464,4.0,17.000000,4.000000,7.593495,2.165884,1.000000,1.132409e+07,...,0,0,0,0,0,0,0,0,0,0
30460,2015-06-29,4.007333,3.496508,8.0,16.000000,1.000000,7.590347,2.302585,2.000000,2.481385e+07,...,0,0,0,0,0,0,0,0,0,0
30461,2015-06-30,3.610918,2.995732,5.0,16.000000,1.000000,7.590852,2.197225,3.000000,6.050065e+06,...,0,0,0,0,0,0,0,0,0,0
30462,2015-06-30,3.871201,3.433987,23.0,25.000000,4.000000,7.608871,2.397895,1.000000,9.629358e+06,...,0,0,0,0,0,0,0,0,0,0
30463,2015-06-30,4.043051,3.401197,13.0,14.000000,1.000000,7.601402,2.484907,3.000000,9.249237e+06,...,0,0,0,0,0,0,0,0,0,0
30464,2015-06-30,4.043051,3.951244,19.0,19.000000,1.000000,7.609367,2.165884,1.000000,4.441296e+06,...,0,0,0,0,0,0,0,0,0,0
30465,2015-06-30,3.970292,3.466464,13.0,17.000000,1.000000,7.593495,2.165884,1.000000,7.307411e+06,...,0,0,0,0,0,0,0,0,0,0
30466,2015-06-30,3.806662,3.332205,7.0,9.000000,1.000000,7.588324,1.945910,3.000000,1.005305e+07,...,0,0,0,0,0,0,0,0,1,0
30467,2015-06-30,4.465908,4.094345,3.0,9.000000,2.000000,7.567863,2.397895,3.000000,7.307411e+06,...,0,0,0,0,0,0,0,0,1,0
30468,2015-06-30,3.828641,3.466464,10.0,20.000000,1.000000,7.593495,2.165884,1.000000,2.553630e+07,...,0,0,0,0,0,0,0,0,0,0
30469,2015-06-30,4.174387,3.496508,5.0,15.000000,1.000000,7.602401,2.484907,2.000000,6.050065e+06,...,0,0,0,0,0,0,0,0,0,0
30470,2015-06-30,3.784190,3.367296,1.0,9.000000,1.000000,7.584773,1.945910,2.000000,4.395333e+06,...,0,0,0,0,0,0,0,0,1,0

Normalize features

# Fit a linreg on the training set

In [13]:
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor

regr = linear_model.LinearRegression()
rf   = RandomForestRegressor()

regr.fit(X_train_clean, y_train)
rf.fit(X_train_clean, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [14]:
# The mean squared error
print("Root mean squared error REGRESSION: %.2f"
      % np.sqrt(np.mean((regr.predict(X_train_clean) - y_train) ** 2)))

print("Root mean squared error RANDOM FOREST: %.2f"
      % np.sqrt(np.mean((rf.predict(X_train_clean) - y_train) ** 2)))

Root mean squared error REGRESSION: 0.47
Root mean squared error RANDOM FOREST: 0.21

# Cross Validation

In [27]:
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import TimeSeriesSplit



def cv_macro_enet(alpha, l1_ratio, n_splits, X, y):

    tscv = TimeSeriesSplit(n_splits=n_splits)
    enet_model = ElasticNet(max_iter=5000, alpha=alpha, l1_ratio=l1_ratio)

    rmse = []
    dims = []
    for train_index, test_index in tscv.split(X):

        enet_model.fit(X.iloc[train_index,:], y.iloc[train_index])
        pred = enet_model.predict(X.iloc[test_index,:])

        rmse.append(np.sqrt(np.mean( (pred-y.iloc[test_index])**2)))
        dims.append((len(y.iloc[train_index].values), len(y.iloc[test_index])))
    
    return [np.mean(rmse), pred, y.iloc[test_index]]

In [28]:
alphas = np.arange(0.01, 1, 0.05)
l1_rats = np.arange(0, 1, 0.1)
print alphas, l1_rats

[ 0.01  0.06  0.11  0.16  0.21  0.26  0.31  0.36  0.41  0.46  0.51  0.56
  0.61  0.66  0.71  0.76  0.81  0.86  0.91  0.96] [ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9]

In [29]:
cv_result = [ {'alpha': a, 'l1_rat':l, 'rmse': cv_macro_enet(a,l,10, X_train_clean, y_train)[0]} for a in alphas for l in l1_rats ]

/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/sklearn/linear_model/coordinate_descent.py:470: UserWarning: Coordinate descent with alpha=0 may lead to unexpected results and is discouraged.
  positive)
/home/roman/anaconda2/envs/python_cursus/lib/python2.7/site-packages/sklearn/linear_model/coordinate_descent.py:484: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)

KeyboardInterrupt:

In [ ]:
pd.DataFrame(cv_result).sort_values('rmse')

# Predict on the Testset

In [19]:
regr.fit(X_train_clean, y_train)
submission_pred = regr.predict(X_test_clean)

In [20]:
submission_pred = np.exp(submission_pred)-1

In [21]:
print submission_pred

[ 4991539.00407912  8279064.40383018  5144493.49472311 ...,
  5244539.96523729  4903309.58134972  8281197.93082849]

In [22]:
df_sub = pd.DataFrame()
df_sub['id'] = df_test['id'].copy()
df_sub['price_doc'] = submission_pred
df_sub.to_csv('./submission4_with_macro.csv')

# Deviations from MacroPrice

In [21]:
from sklearn import linear_model
regr_dev = linear_model.LinearRegression()

In [22]:
y_train_dev = y_train - X_train_clean['macro_price'].values

In [23]:
X_train_dev = X_train.drop('macro_price', axis=1)

In [28]:
X_train_dev
#regr_dev.fit(X_train_dev, y_train_dev.values)

,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,...,cafe_count_5000_price_2500,cafe_count_5000_price_4000,cafe_count_5000_price_high,big_church_count_5000,church_count_5000,mosque_count_5000,leisure_count_5000,sport_count_5000,market_count_5000,month_year
0,2011-08-20,43,27.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,9,4,0,13,22,1,0,52,4,8_2011
1,2011-08-23,34,19.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,15,3,0,15,29,1,10,66,14,8_2011
2,2011-08-27,43,29.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,10,3,0,11,27,0,4,67,10,8_2011
3,2011-09-01,89,50.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,11,2,1,4,4,0,0,26,3,9_2011
4,2011-09-05,77,77.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,319,108,17,135,236,2,91,195,14,9_2011
5,2011-09-06,67,46.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,...,62,14,1,53,78,1,20,113,17,9_2011
6,2011-09-08,25,14.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,81,16,3,38,80,1,27,127,8,9_2011
7,2011-09-09,44,44.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,9,4,0,11,18,1,0,47,4,9_2011
8,2011-09-10,42,27.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,19,8,1,18,34,1,3,85,11,9_2011
9,2011-09-13,36,21.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,19,13,0,10,20,1,3,67,1,9_2011
10,2011-09-16,36,19.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0,5,9,0,2,17,6,9_2011
11,2011-09-16,38,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,8,3,0,10,9,0,0,35,4,9_2011
12,2011-09-17,43,28.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,13,9,1,7,15,0,2,47,0,9_2011
13,2011-09-19,31,31.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,254,108,22,57,102,1,72,166,7,9_2011
14,2011-09-19,31,21.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,88,19,2,63,100,0,28,132,14,9_2011
15,2011-09-20,51,31.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,...,6,1,0,9,21,0,1,53,9,9_2011
16,2011-09-20,47,31.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,10,2,0,7,23,0,4,62,13,9_2011
17,2011-09-20,42,28.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,32,6,0,13,33,1,10,72,12,9_2011
18,2011-09-22,59,33.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0,6,9,0,2,17,6,9_2011
19,2011-09-22,44,29.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,9,2,0,10,14,0,2,51,5,9_2011
20,2011-09-22,74,44.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,1,5,0,0,0,0,9_2011
21,2011-09-22,39,39.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,...,18,3,0,12,14,0,1,64,9,9_2011
22,2011-09-23,48,34.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,16,4,1,11,10,0,1,55,8,9_2011
23,2011-09-23,32,18.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,10,1,0,7,21,1,1,42,13,9_2011
24,2011-09-23,34,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,...,20,4,1,8,9,0,1,56,8,9_2011
25,2011-09-24,45,29.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,...,23,15,1,11,23,1,4,70,1,9_2011
26,2011-09-26,35,20.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,16,5,0,13,25,1,3,84,4,9_2011
27,2011-09-26,38,20.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,0,2,10,0,1,11,2,9_2011
28,2011-09-26,73,38.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,...,20,3,0,17,35,0,9,98,7,9_2011
29,2011-09-27,42,27.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,...,15,2,0,12,17,0,3,73,5,9_2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30441,2015-06-27,113,1.0,26.0,26.0,1.0,2015.0,4.0,1.0,1.0,...,371,141,26,150,249,2,105,203,13,6_2015
30442,2015-06-27,40,40.0,2.0,12.0,4.0,2015.0,1.0,10.0,1.0,...,0,0,0,1,7,1,0,12,1,6_2015
30443,2015-06-27,79,NaN,17.0,17.0,1.0,NaN,3.0,79.0,1.0,...,7,2,0,5,14,0,3,17,2,6_2015
30444,2015-06-27,85,NaN,20.0,25.0,4.0,2016.0,3.0,1.0,1.0,...,13,4,1,5,7,0,1,38,5,6_2015
30445,2015-06-27,47,47.0,19.0,25.0,1.0,2016.0,1.0,1.0,1.0,...,99,57,12,23,42,1,13,123,7,6_2015
30446,2015-06-27,82,82.0,8.0,8.0,6.0,2017.0,2.0,1.0,1.0,...,2,2,0,2,9,0,0,7,2,6_2015
30447,2015-06-27,64,NaN,15.0,17.0,1.0,NaN,2.0,1.0,NaN,...,7,2,0,5,14,0,3,17,2,6_2015
30448,2015-06-27,74,NaN,8.0,17.0,1.0,NaN,3.0,1.0,NaN,...,1,0,0,1,7,0,0,8,0,6_2015
30449,2015-06-27,47,47.0,7.0,25.0,1.0,2015.0,1.0,1.0,1.0,...,99,57,12,23,42,1,13,123,7,6_2015
30450,2015-06-29,65,NaN,5.0,0.0,1.0,NaN,2.0,0.0,NaN,...,20,4,0,13,28,1,3,84,5,6_2015
30451,2015-06-29,37,NaN,3.0,3.0,1.0,0.0,1.0,1.0,1.0,...,0,0,0,0,0,0,0,0,0,6_2015
30452,2015-06-29,38,19.0,7.0,17.0,1.0,2006.0,1.0,7.0,3.0,...,26,12,0,8,23,1,4,67,2,6_2015
30453,2015-06-29,45,1.0,6.0,15.0,6.0,2015.0,1.0,1.0,1.0,...,2,1,0,3,8,1,0,20,3,6_2015
30454,2015-06-29,40,26.0,3.0,9.0,2.0,1972.0,2.0,5.0,3.0,...,25,3,0,17,29,0,8,90,4,6_2015
30455,2015-06-29,79,79.0,3.0,3.0,1.0,NaN,3.0,1.0,NaN,...,1,1,0,2,12,0,1,10,0,6_2015
30456,2015-06-29,52,30.0,8.0,14.0,1.0,1992.0,2.0,8.0,2.0,...,13,4,1,5,7,0,1,42,6,6_2015
30457,2015-06-29,58,43.0,7.0,9.0,1.0,1979.0,3.0,6.0,3.0,...,5,0,0,8,7,1,1,36,1,6_2015
30458,2015-06-29,50,1.0,7.0,7.0,1.0,2015.0,1.0,0.0,1.0,...,13,1,0,5,15,0,3,35,3,6_2015
30459,2015-06-29,51,NaN,4.0,17.0,4.0,NaN,2.0,1.0,1.0,...,7,2,0,5,14,0,3,17,2,6_2015
30460,2015-06-29,54,32.0,8.0,16.0,1.0,1979.0,2.0,9.0,2.0,...,8,0,0,6,25,0,1,32,8,6_2015
30461,2015-06-30,36,19.0,5.0,16.0,1.0,1980.0,1.0,8.0,3.0,...,41,4,1,4,35,1,6,80,6,6_2015
30462,2015-06-30,47,30.0,23.0,25.0,4.0,2016.0,1.0,10.0,1.0,...,99,57,12,23,42,1,13,123,7,6_2015
30463,2015-06-30,56,29.0,13.0,14.0,1.0,2001.0,2.0,11.0,3.0,...,14,2,0,13,12,0,1,53,6,6_2015
30464,2015-06-30,56,51.0,19.0,19.0,1.0,2017.0,2.0,1.0,1.0,...,25,3,0,14,29,1,4,90,6,6_2015
30465,2015-06-30,52,NaN,13.0,17.0,1.0,NaN,2.0,1.0,1.0,...,371,141,26,150,249,2,105,203,13,6_2015
30466,2015-06-30,44,27.0,7.0,9.0,1.0,1975.0,2.0,6.0,3.0,...,15,5,0,15,26,1,2,84,6,6_2015
30467,2015-06-30,86,59.0,3.0,9.0,2.0,1935.0,4.0,10.0,3.0,...,313,128,24,98,182,1,82,171,15,6_2015
30468,2015-06-30,45,NaN,10.0,20.0,1.0,NaN,1.0,1.0,1.0,...,1,1,0,2,12,0,1,11,1,6_2015
30469,2015-06-30,64,32.0,5.0,15.0,1.0,2003.0,2.0,11.0,2.0,...,22,1,1,6,31,1,4,65,7,6_2015
30470,2015-06-30,43,28.0,1.0,9.0,1.0,1968.0,2.0,6.0,2.0,...,5,2,0,7,16,0,9,54,10,6_2015